name: Create Release
on:
  workflow_dispatch:
    inputs:
      release_tag:
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y $(find . -name apt-requirements.txt | xargs sed -e "s/#.*//g")
      - name: Build
        run: |
          git tag ${{ inputs.release_tag }}
          bazel build --stamp :release
      - name: Test
        run: |
          echo "No tests to run"
          # bazel test //...
      - name: Publish Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          bazel run :release -- ${{ inputs.release_tag }}
